spring:
  profiles:
    active: dev
  output:
    ansi:
      enabled: always
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
#    root: WARN
    com.tsingyun: INFO

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/leave?useSSL=false
    username: root
    password: pvdmadmin
  devtools:
    restart:
      enabled: true

flowable:
  check-process-definitions: true
